### ISSUE TITLE
No icon set in app window

### ISSUE THREAD

**Issue by csmart** [kororaproject/kp-korora-welcome#2]
The desktop can see the icon when searching for Welcome but opening it there's no icon set in the window. I assume we need to do this in python/lens.
![Uploading welcome-icon.png . . .]()

**Comment by firnsy** [comment]
KDE?

**Comment by csmart** [comment]
There is no icon in Cinnamon or GNOME window app at all, although they do show the correct icon in the taskbar which it's getting from the .desktop file. Xfce shows no icon in the app bar and shows a generic "app window" icon in the taskbar.

So my guess is because there's no icon set, KDE is helpfully telling you it's an X app which is overriding the icon in the taskbar. I assume if we set the icon correctly in our app then KDE will stop being helpful, and it will show up in GNOME and Cinnamon too.
